# Generated by Django 4.2.2 on 2023-06-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, unique=True, verbose_name="이메일"),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="닉네임")),
                ("image", models.ImageField(blank=True, upload_to="users")),
                (
                    "bio",
                    models.CharField(blank=True, max_length=100, verbose_name="자기소개"),
                ),
                (
                    "sigungu",
                    models.IntegerField(blank=True, null=True, verbose_name="시군구"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="나이"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자 여부")),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spots.area",
                        verbose_name="시도",
                    ),
                ),
                (
                    "followings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
