# Generated by Django 4.2.2 on 2023-06-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Joriro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="joriro/%Y/%m/", verbose_name="이미지"),
                ),
                (
                    "model",
                    models.PositiveIntegerField(
                        choices=[(1, "품질"), (2, "보통"), (3, "성능")],
                        default=2,
                        verbose_name="모델",
                    ),
                ),
                (
                    "place",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "6.25"),
                            (2, "해운대"),
                            (3, "한라산"),
                            (4, "판문점"),
                            (5, "석굴암"),
                        ],
                        verbose_name="여행지",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="결과"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joriros",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
    ]
